### ISSUE TITLE
Release Candidate: Feature-set

### ISSUE THREAD

**Issue by matthewjamesr** [MyHush/hush-ng#1]
We need to flesh-out the list of must-have features for HushNG. These will be included in the release candidate build and should only include the required features for such a build, culminating in a v1.0 release.  V1.5 will include Messenger, while v2.0 will include `hushjs` to give users the ability to not run a full-node.

Comment with your features (not listed) below and it will be added if agreed on.

---

## RC Features
* Installer
  * Option: Data-dir
  * Option: HushOnTor
  * Generate hush.conf - with seed nodes.
* Self-updater
* Encryption
  * Encrypt wallet.dat with a user-generated seed.
* O/S-level Notifications
  * On transaction recieved
  * On new wallet/node version

**Comment by leto** [comment]
This sounds like a great plan, let's start carving it into smaller parts on hacking on code! :+1:

**Comment by madbuda** [comment]
updated seeds in chainparams or a few `addnode=nodea` in the .conf

An export transactions would be a nice to have, simple dump to csv or json

**Comment by matthewjamesr** [comment]
@leto I will be programming everything for this. HushNG is going to be a Vuejs-based application running inside Electronjs to give it OS-level accesses to things like filesystems, notifications, etc. The only thing I am not sure yet is how we should do the updater. Should be as simple as having `.json` file in hush.git/hush-ng.git that gets updated on every build.

**hush.git**
```
{
   "package": "Hush Core",
   "liveVersion": 1.3,
   "devVersion": 1.4,
   "devBranch": "https://github.com/myhush/hush.git+development"
}

Then HushNG can ping those two JSON files onLaunch and periodically and compare against local versions. Thoughts?

**Comment by madbuda** [comment]
Export Keys
Create cold storage - ask for usb drive and generate a new encrypted wallet.dat, copy wallet and display a few t_addresses and a z_address

**Comment by madbuda** [comment]
@matthewjamesr for the updater we can use bintray, we already have an org and 1TB/month of xfer

**Comment by matthewjamesr** [comment]
@madbuda Export Keys: may be better served through exporting that data in a txt/pdf file. We can add nice QR codes, etc. etc.

**Comment by matthewjamesr** [comment]
Bintray will not be a solution as it would only affect linux/unix user-base. Whereas I can just ping the gitrepo through GH Pages and inspect that JSON file, trigger update.
